print("Введите название товара")
good = str(44)
print('Введите количество (кг)')
kg = float(4.5)
print('Введите цену')
price = float(34)
print('Введите сумму платежа')
summa = float(1000)
ch = (summa - (price * kg))
print('ЧЕК')
print(good, 'вес', kg, 'кг', 'стомость', price, 'руб/кг', )
print('Итого', (price * kg))
print("Получено", summa, 'руб.')
print('Сумма сдачи', ch, 'руб.')
